version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "test-harness-sigv4-enabled"
s3_prefix = "ipvreturn-test-harness"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "CodeSigningConfigArn=\"none\" Environment=\"dev\" PermissionsBoundary=\"none\" SecretPrefix=\"none\" VpcStackName=\"vpc-cri\" BackendStack=\"ipvreturn-api\""
image_repositories = []
